chore: Adds predefined action for emulator

diff --git a/.github/workflows/android-e2e-test.yml b/.github/workflows/android-e2e-test.yml
--- a/.github/workflows/android-e2e-test.yml
+++ b/.github/workflows/android-e2e-test.yml
@@ -24,38 +24,27 @@ jobs:
         with:
           node-version: 14
           cache: 'yarn'
-      - name: Download Android Emulator Image
-        run: |
-          echo "y" | $ANDROID_HOME/tools/bin/sdkmanager --install "system-images;android-29;google_apis;x86"
-          echo "no" | $ANDROID_HOME/tools/bin/avdmanager create avd --force --name e2e_emulator --device "Nexus 5X" -k 'system-images;android-29;google_apis;x86'
-          echo "################\n  EMULATORS\n################"
-          $ANDROID_HOME/emulator/emulator -list-avds
-      # - name: Install root node dependencies
-      #   run: yarn
-      # - name: Install node dependencies
-      #   working-directory: ${{ env.WORKING_DIRECTORY }}
-      #   run: yarn
-      # - name: Build app
-      #   working-directory: ${{ env.WORKING_DIRECTORY }}
-      #   run: yarn build-e2e-android
-      - name: Run Android Emulator
-        timeout-minutes: 10
-        continue-on-error: true
-        run: |
-          echo "Starting emulator"
-          nohup $ANDROID_HOME/emulator/emulator -avd e2e_emulator -no-window&
-          $ANDROID_HOME/platform-tools/adb wait-for-device shell 'while [[ -z $(getprop sys.boot_completed | tr -d '\r') ]]; do sleep 1; done; input keyevent 82'
-          $ANDROID_HOME/platform-tools/adb devices
-          echo "Emulator started"
+      - name: Install root node dependencies
+        run: yarn
+      - name: Install node dependencies
+        working-directory: ${{ env.WORKING_DIRECTORY }}
+        run: yarn
+      - name: Build app
+        working-directory: ${{ env.WORKING_DIRECTORY }}
+        run: yarn build-e2e-android
       - name: Make artifacts dir
         working-directory: ${{ env.WORKING_DIRECTORY }}
         run: mkdir artifacts
       - name: Take screenshot
         working-directory: ${{ env.WORKING_DIRECTORY }}
         run: $ANDROID_HOME/platform-tools/adb exec-out screencap -p > artifacts/screen.png
-      # - name: Test app
-      #   working-directory: ${{ env.WORKING_DIRECTORY }}
-      #   run: yarn test-e2e-android || echo "failed"
+      - name: Run emulator and tests
+        uses: reactivecircus/android-emulator-runner@v2
+        with:
+          working-directory: ${{ env.WORKING_DIRECTORY }}
+          api-level: 29
+          avd-name: e2e_emulator
+          script: yarn test-e2e-android || echo "failed"
       - uses: actions/upload-artifact@v2
         with:
           name: android-fail-screen-shoots
