chore: Adds taking screenshot and omit error

diff --git a/.github/workflows/android-e2e-test.yml b/.github/workflows/android-e2e-test.yml
--- a/.github/workflows/android-e2e-test.yml
+++ b/.github/workflows/android-e2e-test.yml
@@ -47,9 +47,12 @@ jobs:
           $ANDROID_HOME/platform-tools/adb wait-for-device shell 'while [[ -z $(getprop sys.boot_completed | tr -d '\r') ]]; do sleep 1; done; input keyevent 82'
           $ANDROID_HOME/platform-tools/adb devices
           echo "Emulator started"
+      - name: Take screenshot
+        working-directory: ${{ env.WORKING_DIRECTORY }}
+        run: adb exec-out screencap -p > artifacts/screen.png
       - name: Test app
         working-directory: ${{ env.WORKING_DIRECTORY }}
-        run: yarn test-e2e-android
+        run: yarn test-e2e-android || echo "failed"
       - uses: actions/upload-artifact@v2
         with:
           name: android-fail-screen-shoots
